//import org.postgresql.Driver;
import java.sql.*;

public class JDBCRunner {
    public static void main(String[] args) throws SQLException{
        Class <Driver> driverClass = Driver.class;
        String sql = """
        INSERT INTO info (data)
        VALUES ('autogenerated');
        """;
        try (Connection connection = ConnectionManager.open();
        Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE)) {
            System.out.println(connection.getSchema());
            System.out.println(connection.getTransactionIsolation());

            int executeSet = statement.executeUpdate(sql, Statement.RETURN_GENERATED_KEYS);
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()){
                int generatedId = generatedKeys.getInt(1);
                System.out.println(generatedId);
            }

//            while (executeResult.next()){
//                System.out.println(executeResult.getLong("id"));
//                System.out.println(executeResult.getString("passenger_no"));
//                System.out.println(executeResult.getBigDecimal("cost"));
//                System.out.println("--------");
//            }
        }

    }
}
